[package]
name = "data_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

office = "0.8.1"
serde = {version = "1.0.157", features = ["derive", "rc"]}
gnuplot = "0.0.37"